export PACKER_LOG_PATH=/opt/packer/logs/test_log_build.log
export PACKER_LOG=1
export http_proxy=http://username:password@proxy.hola.com:8080
export https_proxy=http://username:password@proxy.hola.com:8080
#export PKR_VAR_subscription_id=$(az account show -o tsv --query 'id')
#export PKR_VAR_tenant_id=$(az account show -o tsv --query 'tenantId')
#export PKR_VAR_connection_password="password1"
#export PKR_VAR_connection_password="password1"
export PKR_VAR_aws_access_key_id="HOLAHOLAHOLAHOLA1"
export PKR_VAR_aws_secret_access_key="fadoijas14138035jaosidjfaiefja0w89er02381"
